CREATE OR REPLACE FUNCTION get_exchange_rate(
    p_currency IN VARCHAR2
) RETURN NUMBER
IS
    v_rate EXCHANGERATE.RATE_TO_PLN%TYPE;
BEGIN
    SELECT RATE_TO_PLN
    INTO v_rate
    FROM EXCHANGERATE
    WHERE CURRENCY = UPPER(p_currency)
    ORDER BY RATE_DATE DESC
    FETCH FIRST 1 ROWS ONLY;

    RETURN v_rate;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
    WHEN OTHERS THEN
        RETURN NULL;
END;
/

SELECT get_exchange_rate('USD') FROM dual;
