create or replace TRIGGER trg_archive_investor
BEFORE DELETE ON INVESTOR
FOR EACH ROW
DECLARE
    v_user VARCHAR2(50);
BEGIN
    v_user := SYS_CONTEXT('USERENV', 'SESSION_USER');
    INSERT INTO INVESTOR_ARCHIVE 
      (INVESTOR_ID, CLIENT_CODE, NAME, EMAIL, PHONE, NATIONAL_ID, CREATED_AT, DELETED_AT, DELETED_BY)
    VALUES 
      (:OLD.INVESTOR_ID, :OLD.CLIENT_CODE, :OLD.NAME, :OLD.EMAIL, :OLD.PHONE, :OLD.NATIONAL_ID, :OLD.CREATED_AT, SYSTIMESTAMP, v_user);
END;