CREATE OR REPLACE TRIGGER trg_archive_company
BEFORE DELETE ON COMPANY
FOR EACH ROW
DECLARE
    v_user VARCHAR2(50);
BEGIN
    v_user := SYS_CONTEXT('USERENV', 'SESSION_USER');
    INSERT INTO COMPANY_ARCHIVE
      (COMPANY_ID, NAME, TICKER, SECTOR, COUNTRY, WEBSITE, DELETED_AT, DELETED_BY)
    VALUES
      (:OLD.COMPANY_ID, :OLD.NAME, :OLD.TICKER, :OLD.SECTOR, :OLD.COUNTRY, :OLD.WEBSITE, SYSTIMESTAMP, v_user);
END;
/
